cleanup (#3)
* add math, remove shapelib

* removed stb definitions in image.cpp, do not include predicates yet

* warning fixes

* use trees namespace for kdtree

* disable linter

diff --git a/.github/workflows/cc.yml b/.github/workflows/cc.yml
--- a/.github/workflows/cc.yml
+++ b/.github/workflows/cc.yml
@@ -28,19 +28,19 @@ jobs:
     - name: build
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
-    - name: format
-      uses: cpp-linter/cpp-linter-action@v2
-      id: linter
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        style: file
+    # - name: lint
+    #   uses: cpp-linter/cpp-linter-action@v2
+    #   id: linter
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   with:
+    #     style: file
 
-    - name: check failure
-      if: steps.linter.outputs.checks-failed > 0
-      run: |
-        echo "Some files failed the linting checks!"
-        exit 1
+    # - name: check failure
+    #   if: steps.linter.outputs.checks-failed > 0
+    #   run: |
+    #     echo "Some files failed the linting checks!"
+    #     #exit 1
 
     - name: test
       working-directory: ${{github.workspace}}/build
